### ISSUE TITLE
ES Module failure

### ISSUE THREAD

**Issue by FrancoLinares** [magiclen/ts-short-crypt#10]
I tried to use this package but I can't get it to run.
There is a problem with the ESM.

```
require("short-crypt") 

const sc = new ShortCrypt('2');
const cipher1 = sc.encryptToURLComponent('plaintext');

console.log(cipher1);
```

### ERROR
Error: require() of ES Module /app/available_modules/1701049416000/short-crypt/lib/lib.js from /app/index.js not supported.
Instead change the require of lib.js in /app/index.js to a dynamic import() which is available in all CommonJS modules.
A stack trace for this error could not be retrieved because stack was already called.

**Comment by magiclen** [comment]
Hi, this library only supports ESM, not CommonJS.
