### ISSUE TITLE
Deprecated warning when using decryptURLComponent

### ISSUE THREAD

**Issue by rdzidziguri** [magiclen/ts-short-crypt#3]
When using this method. Bundle the code using any bundler (ESBuild is used in this case). Once you run the application, you will see this warning
```shell
(node:25668) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```
The error originates from calling 
```JavaScript
base64.encode(encrypted).replace(/[+/]/g, (m0) => {
          return m0 === "+" ? "-" : "_";
        }).replace(/=/g, "");
```
The issue is using `hi-base64` lib that internally uses `new Buffer` you do not need this in newer NodeJS

**Comment by magiclen** [comment]
Make sense. I replaced `hi-base32` and `hi-base64` with [`rfc4648`](https://www.npmjs.com/package/rfc4648). The warning should be gone now.

**Comment by rdzidziguri** [comment]
I confirm the warning is gone in a prod build now. Thank you for your quick response and resolution.
