### ISSUE TITLE
Decrypt functions always return a numeric array instead of the original message

### ISSUE THREAD

**Issue by jalamprea** [magiclen/ts-short-crypt#4]
If you encrypt a message, no matter if it is encryptToURLComponent or encryptToQRCodeAlphanumeric, when you decrypt the key, using the respective decryptURLComponent or decryptQRCodeAlphanumeric, the response is always a numeric array, not the original expected string

**Comment by magiclen** [comment]
You can use `Buffer.from(decrypedData).toString('utf8')` in Node.js or `new TextDecoder().decode(Uint8Array.from(decrypedData))` in Web Browser to get the message (string) that you previously encrypted.

I'm thinking to use Uint8Array to replace the number array in the next major verson. It would be more convenience.

**Comment by magiclen** [comment]
`number[]` has been replaced with `Uint8Array` since 2.0.0.
