### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED

### ISSUE THREAD

**Issue by dhianica** [magiclen/ts-short-crypt#6]
Thanks for your update,

I have an issue, after update.

I get an error ERR_PACKAGE_PATH_NOT_EXPORTED, after your update a package.json 
from
```
"main": "lib/short_crypt.js",
"types": "lib/short_crypt.d.ts",
```

to
```
"type": "module",
  "exports": "./lib/lib.js",
  "types": "./lib/lib.d.ts",
  "engines": {
    "node": ">=16"
  },
```

![image](https://user-images.githubusercontent.com/21213646/232255465-a5138f2a-dbe5-4446-8f62-4be7decc1204.png)

when i check in my node_modules, i cannot found a file  ***./lib/lib.js***

![image](https://user-images.githubusercontent.com/21213646/232255544-52256f67-946d-4535-a3ca-c9dc414f1a7a.png)

Thanks

**Comment by magiclen** [comment]
It should be fixed now. Thanks for your report.

**Comment by dhianica** [comment]
thanks, for your updated
